db: 
  host: localhost
  port: 3306
  user: efip
  password: lapapa36
  database: efip
host:
  host: 0.0.0.0
  port: 9080
sql:
  sql_get_sucursales: "SELECT id, nombre, direccion, descripcion FROM sucursales"
  sql_get_all_art: "SELECT articulo.idproduct, articulo.barcode, articulo.nombre, articulo.precio, articulo.descripcion, articulo.marca, DATE_FORMAT(inventario.fecha_alta, '%d/%m/%Y') AS fecha_alta , DATE_FORMAT(inventario.fecha_venc , '%d/%m/%Y') AS fecha_venc , inventario.sucursales_id, inventario.cantidad FROM efip.articulo LEFT JOIN efip.inventario ON inventario.barcode  = articulo.barcode WHERE articulo.nombre LIKE '%ibu%'"
